#!/bin/bash

_general() {
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    COMPREPLY=()
    opts="--version -h --help gen create list setup config upgrade help"
    if [[ $COMP_CWORD == "1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case ${COMP_WORDS[1]} in
        (gen)
            _general_gen 2
            return
            ;;
        (create)
            _general_create 2
            return
            ;;
        (list)
            _general_list 2
            return
            ;;
        (setup)
            _general_setup 2
            return
            ;;
        (config)
            _general_config 2
            return
            ;;
        (upgrade)
            _general_upgrade 2
            return
            ;;
        (help)
            _general_help 2
            return
            ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_gen() {
    opts="--path -p --name -n --template -t --output -o --target --version -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --path|-p)
            COMPREPLY=( $(compgen -d -- "$cur") )
            return
        ;;
        --name|-n)
            
            return
        ;;
        --template|-t)
            COMPREPLY=( $(compgen -W "$("${COMP_WORDS[0]}" ---completion gen -- --template "${COMP_WORDS[@]}")" -- "$cur") )
            return
        ;;
        --output|-o)
            COMPREPLY=( $(compgen -d -- "$cur") )
            return
        ;;
        --target)
            COMPREPLY=( $(compgen -W "$("${COMP_WORDS[0]}" ---completion gen -- --target "${COMP_WORDS[@]}")" -- "$cur") )
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_create() {
    opts="--template -t --path -p --version -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --template|-t)
            
            return
        ;;
        --path|-p)
            COMPREPLY=( $(compgen -d -- "$cur") )
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_list() {
    opts="--version -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_setup() {
    opts="--repo -r --global -g --xcodeproj -x --target -t --company -c --version -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --repo|-r)
            COMPREPLY=( $(compgen -W "$("${COMP_WORDS[0]}" ---completion setup -- --repo "${COMP_WORDS[@]}")" -- "$cur") )
            return
        ;;
        --global|-g)
            
            return
        ;;
        --xcodeproj|-x)
            
            return
        ;;
        --target|-t)
            
            return
        ;;
        --company|-c)
            
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config() {
    opts="--version -h --help print reset repo use"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case ${COMP_WORDS[$1]} in
        (print)
            _general_config_print $(($1+1))
            return
            ;;
        (reset)
            _general_config_reset $(($1+1))
            return
            ;;
        (repo)
            _general_config_repo $(($1+1))
            return
            ;;
        (use)
            _general_config_use $(($1+1))
            return
            ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config_print() {
    opts="--version -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config_reset() {
    opts="--version -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config_repo() {
    opts="--as --version -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --as)
            
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config_use() {
    opts="--executable -e --for --version -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --executable|-e)
            COMPREPLY=( $(compgen -W "$("${COMP_WORDS[0]}" ---completion config use -- --executable "${COMP_WORDS[@]}")" -- "$cur") )
            return
        ;;
        --for)
            
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_upgrade() {
    opts="--version -h --help"
    opts="$opts $("${COMP_WORDS[0]}" ---completion upgrade -- version "${COMP_WORDS[@]}")"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_help() {
    opts="--version"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_bootstrap() {
    opts="--version -h --help make config"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case ${COMP_WORDS[$1]} in
        (make)
            _general_bootstrap_make $(($1+1))
            return
            ;;
        (config)
            _general_bootstrap_config $(($1+1))
            return
            ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_test() {
    opts="--version -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

 -F _general general
