#!/bin/bash

_general() {
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    COMPREPLY=()
    opts="gen create list setup config upgrade help -h --help"
    if [[ $COMP_CWORD == "1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case ${COMP_WORDS[1]} in
        (gen)
            _general_gen 2
            return
            ;;
        (create)
            _general_create 2
            return
            ;;
        (list)
            _general_list 2
            return
            ;;
        (setup)
            _general_setup 2
            return
            ;;
        (config)
            _general_config 2
            return
            ;;
        (upgrade)
            _general_upgrade 2
            return
            ;;
        (help)
            _general_help 2
            return
            ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_gen() {
    opts="--path -p --name -n --template -t --output -o --target -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --path|-p)
            COMPREPLY=( $(compgen -d -- "$cur") )
            return
        ;;
        --name|-n)
            
            return
        ;;
        --template|-t)
            COMPREPLY=( $(compgen -W "$(general-ios ---completion gen -- --template "$COMP_WORDS")" -- "$cur") )
            return
        ;;
        --output|-o)
            COMPREPLY=( $(compgen -d -- "$cur") )
            return
        ;;
        --target)
            COMPREPLY=( $(compgen -W "$(general-ios ---completion gen -- --target "$COMP_WORDS")" -- "$cur") )
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_create() {
    opts="--template -t --path -p -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --template|-t)
            
            return
        ;;
        --path|-p)
            COMPREPLY=( $(compgen -d -- "$cur") )
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_list() {
    opts="-h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_setup() {
    opts="--repo -r --global -g --xcodeproj -x --target -t --company -c -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --repo|-r)
            COMPREPLY=( $(compgen -W "$(general-ios ---completion setup -- --repo "$COMP_WORDS")" -- "$cur") )
            return
        ;;
        --global|-g)
            
            return
        ;;
        --xcodeproj|-x)
            
            return
        ;;
        --target|-t)
            
            return
        ;;
        --company|-c)
            
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config() {
    opts="print reset repo use -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case ${COMP_WORDS[$1]} in
        (print)
            _general_config_print $(($1+1))
            return
            ;;
        (reset)
            _general_config_reset $(($1+1))
            return
            ;;
        (repo)
            _general_config_repo $(($1+1))
            return
            ;;
        (use)
            _general_config_use $(($1+1))
            return
            ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config_print() {
    opts="-h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config_reset() {
    opts="-h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config_repo() {
    opts="--as -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --as)
            
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_config_use() {
    opts="--executable -e --for -h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    case $prev in
        --executable|-e)
            COMPREPLY=( $(compgen -W "$(general ---completion config use -- --executable "$COMP_WORDS")" -- "$cur") )
            return
        ;;
        --for)
            
            return
        ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_upgrade() {
    opts="-h --help"
    opts="$opts $(general ---completion upgrade -- version "$COMP_WORDS")"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_help() {
    opts="-h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

_general_test() {
    opts="-h --help"
    if [[ $COMP_CWORD == "$1" ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

 -F _general general
