company: Rosberry
outputs:
  - templateName: rsb_mvp_vm_module
    path: Classes/Presentation/Modules
  - templateName: rsb_mvp_vm_list_module
    path: Classes/Presentation/Modules
  - templateName: rsb_generic_list_module
    path: Classes/Presentation/Modules
  - templateName: rsb_service
    path: Classes/BusinessLogic/Services
